# Generated by Django 4.0.6 on 2022-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
