# Generated by Django 4.0.6 on 2022-07-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_client_address_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='fieldName',
        ),
    ]
