# Generated by Django 4.0.6 on 2022-07-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_amount_alter_loan_loan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanschedule',
            name='date_schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
