# Generated by Django 4.0.6 on 2022-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_loan_date_alter_loan_repayment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='principle_amount',
            field=models.FloatField(max_length=300, null=True),
        ),
    ]
