# Generated by Django 4.0.6 on 2022-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_principle_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='principle_amount',
            new_name='interest_amount',
        ),
    ]
