# Generated by Django 4.0.6 on 2022-07-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_rename_principle_amount_loan_interest_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanschedule',
            old_name='amount',
            new_name='pamount',
        ),
        migrations.RenameField(
            model_name='loanschedule',
            old_name='interest',
            new_name='pinterest',
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='principle',
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='status',
        ),
    ]
