# Generated by Django 4.0.6 on 2022-07-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_rename_amount_loanschedule_pamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
    ]
